version: 2

models:
  - name: dim_vendors
    description: "This table contains vendor information"
    columns:
      - name: vendor_id
        description: "A code indicating the provider associated with the trip record. This code is used to identify the company or service that facilitated the taxi trip."
      - name: vendor_name
        description: "The name of the taxi vendor associated with the trip record."